"use strict";
exports.__esModule = true;
var TECHNICAL_INDICATOR;
(function (TECHNICAL_INDICATOR) {
    TECHNICAL_INDICATOR["SMA"] = "SMA";
    TECHNICAL_INDICATOR["EMA"] = "EMA";
    TECHNICAL_INDICATOR["WMA"] = "WMA";
    TECHNICAL_INDICATOR["DEMA"] = "DEMA";
    TECHNICAL_INDICATOR["TEMA"] = "TEMA";
    TECHNICAL_INDICATOR["TRIMA"] = "TRIMA";
    TECHNICAL_INDICATOR["KAMA"] = "KAMA";
    TECHNICAL_INDICATOR["MAMA"] = "MAMA";
    TECHNICAL_INDICATOR["T3"] = "T3";
})(TECHNICAL_INDICATOR || (TECHNICAL_INDICATOR = {}));
exports["default"] = TECHNICAL_INDICATOR;
