enum TIME_SERIES {
  INTRADAY = 'TIME_SERIES_INTRADAY',
  DAILY = 'TIME_SERIES_DAILY',
  DAILY_ADJUSTED = 'TIME_SERIES_DAILY_ADJUSTED',
  WEEKLY = 'TIME_SERIES_WEEKLY',
  MONTHLY = 'TIME_SERIES_MONTHLY',
}

export default TIME_SERIES;
