"use strict";
exports.__esModule = true;
var TIME_SERIES;
(function (TIME_SERIES) {
    TIME_SERIES["INTRADAY"] = "TIME_SERIES_INTRADAY";
    TIME_SERIES["DAILY"] = "TIME_SERIES_DAILY";
    TIME_SERIES["DAILY_ADJUSTED"] = "TIME_SERIES_DAILY_ADJUSTED";
    TIME_SERIES["WEEKLY"] = "TIME_SERIES_WEEKLY";
    TIME_SERIES["MONTHLY"] = "TIME_SERIES_MONTHLY";
})(TIME_SERIES || (TIME_SERIES = {}));
exports["default"] = TIME_SERIES;
